name: subset
description: A new Flutter application.

version: 1.9.0+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  expandable: ^3.0.1
  flutter_staggered_grid_view: ^0.3.0
  sqflite: ^1.1.5
  datetime_picker_formfield: ^1.0.0
  image_picker: 0.6.0+17
  firebase_messaging: ^6.0.9
  firebase_auth: ^0.15.3
  uuid: 2.0.4
  flutter_spinkit: ^3.1.0
  file_picker: ^1.4.3+1
  fluttertoast: ^3.1.3
  url_launcher: ^5.4.1
  photo_view: ^0.9.1
  shared_preferences: ^0.5.6+1
  flutter_image_compress: ^0.6.5+1
  flutter_plugin_pdf_viewer: ^1.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/icons/icon.png
    - assets/icons/doodle.png
    - assets/database/template.db
    - assets/icons/student.png
    - assets/icons/teacher.png
    - assets/icons/default.png
    - assets/icons/parent.png
    - assets/icons/director.png
    - assets/icons/connect.png
    - assets/icons/doubt.png
    - assets/icons/main.png
    - assets/icons/notice.png
    - assets/icons/report.png
    - assets/icons/internet.png
    - assets/icons/title.png
    - assets/icons/pending.png

  fonts:
    - family: OdibeeSans
      fonts:
        - asset: assets/fonts/OdibeeSans-Regular.ttf
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-VariableFont:wght.ttf
    - family: Mukta
      fonts:
        - asset: assets/fonts/RobotoSlab-Light.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
    - family:  Subset
      fonts:
        - asset: assets/icons/Subset.ttf
    - family:  SubsetDoubt
      fonts:
        - asset: assets/icons/SubsetDoubt.ttf
