/// Flutter icons Subset
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Subset
///      fonts:
///       - asset: fonts/Subset.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Subset {
  Subset._();

  static const _kFontFam = 'Subset';

  static const IconData help_and_support = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData fee_payment = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData my_attendance = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData my_coaching = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData my_report = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData photo_gallery = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData rate_us = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData test_series = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData notice = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData assignment = const IconData(0xe80c, fontFamily: _kFontFam);
}
